<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Reddit_Management_System.Service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reddit-Management-System.Application\Reddit-Management-System.Application.csproj" />
    <ProjectReference Include="..\Reddit-Management-System.Data\Reddit-Management-System.Data.csproj" />
    <ProjectReference Include="..\Reddit-Management-System.Domain\Reddit-Management-System.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Common\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
  </ItemGroup>

</Project>
