<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Reddit_Management_System</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
    <PackageReference Include="MiniExcel" Version="1.42.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reddit-Management-System.Application\Reddit-Management-System.Application.csproj" />
    <ProjectReference Include="..\Reddit-Management-System.Data\Reddit-Management-System.Data.csproj" />
    <ProjectReference Include="..\Reddit-Management-System.Repo\Reddit-Management-System.Repo.csproj" />
    <ProjectReference Include="..\Reddit-Management-System.Service\Reddit-Management-System.Service.csproj" />
  </ItemGroup>

</Project>
