<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Pharmacy_Management_System.Data</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pharmacy-Management-System.Application\Pharmacy-Management-System.Application.csproj" />
    <ProjectReference Include="..\Pharmacy-Management-System.Domain\Pharmacy-Management-System.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\Brands\" />
    <Folder Include="Configurations\Permissions\" />
    <Folder Include="DbContexts\" />
    <Folder Include="Migrations\" />
    <Folder Include="Setups\" />
  </ItemGroup>

</Project>
